### ISSUE TITLE
Using .aws/credentials provider doesn't seem to work out of the box

### ISSUE THREAD

**Issue by tcloud8** [fidelity/awsrun#4]
I've come across issues attempting to use awsrun with the default credentials provider. I originally had trouble on a Mac and ran into the same issues in multiple Linux distros, so it doesn't seem to be environment-specific. Please see steps to reproduce below from scratch and debug logs/attempts to fix.

#### Steps to Reproduce
1. Spin up a fresh Ubuntu 20.04 instance (I tried on DigitalOcean separately but using an AWS instance here)
2. ```sudo apt update; sudo apt install -y python3-pip unzip; curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"; unzip awscliv2.zip; sudo aws/install```
3. Place AWS access key ID and secret access key in ~/.aws/credentials under [default] profile (manually or with aws configure command)
4. Confirm ```aws s3 ls``` (or any command these credentials have access to) work
5. Install awsrun ```git clone https://github.com/fidelity/awsrun.git; cd awsrun; sudo pip3 install .```
6. Run ```awsrun --account default aws s3 ls --region us-east-1``` and receive the error ```default/us-east-1: error: expected str, bytes or os.PathLike object, not NoneType``` (see below for output with --log-level DEBUG)
```
2021-01-16 02:30:36,316 awsrun.plugmgr INFO [MainThread] loading plug-in: awsrun.plugins.accts.Identity
2021-01-16 02:30:36,317 awsrun.plugmgr INFO [MainThread] parsed args=Namespace(account_file=None, accounts=['default'], cmd_path=['awsrun.commands.aws'], exclude={}, force=False, include={}, log_level='DEBUG', metadata=None, threads=10) remaining args=['aws', 's3', 'ls', '--region', 'us-east-1']
2021-01-16 02:30:36,317 awsrun.plugmgr INFO [MainThread] loading plug-in: awsrun.plugins.creds.aws.Profile
2021-01-16 02:30:36,321 awsrun.plugmgr INFO [MainThread] parsed args=Namespace(account_file=None, accounts=['default'], cmd_path=['awsrun.commands.aws'], exclude={}, force=False, include={}, log_level='DEBUG', metadata=None, threads=10) remaining args=['aws', 's3', 'ls', '--region', 'us-east-1']
2021-01-16 02:30:36,322 awsrun.cmdmgr INFO [MainThread] loading command at 'awsrun.commands.aws.aws'
... [snip irrelevant boto logs] ...
2021-01-16 02:30:36,334 botocore.session DEBUG [ThreadPoolExecutor-0_0] Setting config variable for profile to 'default'
2021-01-16 02:30:36,338 awsrun.commands.aws.aws INFO [ThreadPoolExecutor-0_0] default-us-east-1: AWS CLI command: ['/usr/local/bin/aws', '--region', 'us-east-1', 's3', 'ls']
2021-01-16 02:30:36,338 botocore.utils DEBUG [ThreadPoolExecutor-0_0] IMDS ENDPOINT: http://169.254.169.254/
2021-01-16 02:30:36,340 botocore.credentials DEBUG [ThreadPoolExecutor-0_0] Skipping environment variable credential check because profile name was explicitly set.
2021-01-16 02:30:36,340 botocore.credentials DEBUG [ThreadPoolExecutor-0_0] Looking for credentials via: assume-role
2021-01-16 02:30:36,340 botocore.credentials DEBUG [ThreadPoolExecutor-0_0] Looking for credentials via: assume-role-with-web-identity
2021-01-16 02:30:36,340 botocore.credentials DEBUG [ThreadPoolExecutor-0_0] Looking for credentials via: sso
2021-01-16 02:30:36,340 botocore.credentials DEBUG [ThreadPoolExecutor-0_0] Looking for credentials via: shared-credentials-file
2021-01-16 02:30:36,341 botocore.credentials INFO [ThreadPoolExecutor-0_0] Found credentials in shared credentials file: ~/.aws/credentials
2021-01-16 02:30:36,341 awsrun.commands.aws.aws INFO [MainThread] default/us-east-1: error: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/awsrun/commands/aws/aws.py", line 538, in regional_collect_results
    result = get_result()
  File "/usr/local/lib/python3.8/dist-packages/awsrun/runner.py", line 946, in fn
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/awsrun/runner.py", line 936, in _wrap_result
    result = fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/awsrun/commands/aws/aws.py", line 500, in regional_execute
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1624, in _execute_child
    env_list.append(k + b'=' + os.fsencode(v))
  File "/usr/lib/python3.8/os.py", line 806, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
default/us-east-1: error: expected str, bytes or os.PathLike object, not NoneType

Processed 1 account in 0:00:00.018664
```

#### Debugging
By making the below change in src/awsrun/commands/aws/aws.py, the command above will work (and the expected s3 output is printed) - but only with the default profile. It's a hack that seems to only work in this specific case because the aws cli tool will find the default creds on its own without the help of awsrun (I think). Note that the debug output log looks exactly the same for the successful run, up to the point of the error (last line of ```Found credentials in shared credentials file: ~/.aws/credentials```). 
```
--- a/src/awsrun/commands/aws/aws.py
+++ b/src/awsrun/commands/aws/aws.py
@@ -484,8 +484,8 @@ class CLICommand(RegionalCommand):
             "AWS_SESSION_TOKEN": creds.token,
         }

-        env = ChainMap(new_vars, os.environ)
-
+        #env = ChainMap(new_vars, os.environ)
+        env = os.environ
```
I could speculate further from here what the exact issue is but I'm not familiar enough with the codebase to say. It seems as though there's some sort of issue setting the environment variables with the default credentials provider. Please let me know if there's anything else I can do to help with this issue.

**Comment by pkazmier** [comment]
Thanks for the report. I'll look at this when I get back later today.

**Comment by pkazmier** [comment]
@tcloud8 I pushed a fix. Can you confirm the issue is resolved for you?

BTW, the argument to `--account` should be your account number instead of the string "default". Although it will work if you are using the `default` profile, if you ever build your own awsrun commands, you likely would want access to the account number that is being processed from within your custom command. 

For example, in the simple command below, we include the account number as part of the output. This is important if we are processing more than one account, so we know which VPC belongs to which account.

```sh
$ cat vpc.py
from awsrun.runner import RegionalCommand

class CLICommand(RegionalCommand):
    def regional_execute(self, session, acct, region):
        ec2 = session.resource("ec2", region_name=region)
        ids = ", ".join(vpc.id for vpc in ec2.vpcs.all())
        return f"{acct}/{region}: {ids}\n"

$ awsrun --account 100200300400 --cmd-path . vpc --region us-east-1
100200300400/us-east-1: vpc-0aea36ed91eae333e

Processed 1 account in 0:00:00.350765
$
```

**Comment by tcloud8** [comment]
This worked - thanks for the quick fix! And good to know about naming accounts - now that I'm up and running I'm going to put multiple accounts into the creds file so I'll name by account number going forward.

Looking forward to exploring the functionality this tool provides - thanks for creating and open-sourcing it.

**Comment by pkazmier** [comment]
Glad to hear it worked.

Once you have multiple accounts defined in your credentials file, be sure to check out the use of an account loader: https://fidelity.github.io/awsrun/cli.html#account-plug-ins You can group your accounts and then execute awsrun commands by group name instead of specifying each one individually on the command line.
